config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root   'static_pages#home'
  get    '/help',      to: 'static_pages#help'
  get    '/about',     to: 'static_pages#about'
  get    '/contact',   to: 'static_pages#contact'
  get    '/signup',    to: 'users#new'
  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'
  resources :users, except: :new do
    member do
      get :following, :followers
    end
  end
  resources :comments,            except: [:index, :show, :new]
  resources :account_activations, only: :edit
  resources :password_resets,     except: [:index, :show, :delete]
  resources :microposts,          only: [:show, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    return unless logged_in?

    @micropost = current_user.microposts.build
    @feed_items = current_user.feed.paginate(page: params[:page])
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/views/static_pages/about.html.erb
<% provide(:title, t('.about')) %>
<h1><%= t('.about') %></h1>
<p>
  <%= t('.about_html',
    url_tutorials: link_to(t('.tutorial_details'), Settings.client.home_link),
    book: link_to(t('.book_details'), Settings.client.book_link),
    screencast: link_to(t('.screencast_details'), Settings.client.screencast_link),
    rails: link_to(t('.rails_details'), Settings.client.ruby_link)) %>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, t('.contact')) %>
<h1><%= t('.contact') %></h1>
<p>
  <%= t('.contact_html', url_contact: link_to(t('.contact_details'), Settings.client.contact_link)) %>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, t('.help')) %>
<h1><%= t('.help') %></h1>
<p>
  <%= t('.help_html',
    url_help: link_to(t('.help_details'), Settings.client.help_link),
    url_book: link_to(t('.book_details_html'), Settings.client.book_link)) %>
</p>

app/views/static_pages/home.html.erb
<% provide(:title, t('.home')) %>
<% if logged_in? %>
  <div class='row'>
    <aside class='col-md-4'>
      <section class='user_info'>
        <%= render 'shared/user_info' %>
      </section>
      <section class='stats'>
        <%= render 'shared/stats' %>
      </section>
      <section class='micropost_form'>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class='col-md-8'>
      <h3><%= t('micropost_feed') %></h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class='center jumbotron'>
    <h1><%= t('.welcome_sample_app') %></h1>
    <h2>
      <%= t('.home_html', url_home: link_to(t('.homepage_details'), Settings.client.home_link)) %>
    </h2>
    <%= link_to t('.sign_up_now'), signup_path, class: 'btn btn-lg btn-primary' %>
  </div>
  <%= link_to image_tag('rails.png', alt: t('.rails_logo')), Settings.client.home_link %>
<% end %>