config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root   'static_pages#home'
  get    '/help',      to: 'static_pages#help'
  get    '/about',     to: 'static_pages#about'
  get    '/contact',   to: 'static_pages#contact'
  get    '/signup',    to: 'users#new'
  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'
  resources :users, except: :new do
    member do
      get :following, :followers
    end
  end
  resources :comments,            except: [:index, :show, :new]
  resources :account_activations, only: :edit
  resources :password_resets,     except: [:index, :show, :delete]
  resources :microposts,          only: [:show, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :load_user,         only: [:edit, :update]
  before_action :valid_token_reset, only: [:edit, :update]
  before_action :check_expiration,  only: [:edit, :update]
  before_action :logged_in_user,    only: :new

  def new
  end

  def create
    if @user = User.find_by(email: params[:password_reset][:email].downcase)
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = I18n.t('messages.success.password_reset.mail_sent')
      redirect_to root_path
    else
      flash.now[:danger] = I18n.t('messages.failed.password_reset.mail_sent')
      render :new
    end
  end

  def edit
  end

  def update
    if params[:user][:password].blank?
      @user.errors.add(:password, I18n.t('messages.failed.password_reset.not_empty'))
    elsif @user.update_attributes(user_params)
      log_in(@user)
      flash[:success] = I18n.t('messages.success.password_reset.has_been_reset')
      redirect_to @user and return
    end
    render :edit
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def load_user
    return if @user = User.find_by(email: params[:email], activated: true)

    flash[:danger] = I18n.t('messages.failed.password_reset.load_user')
    redirect_to root_path
  end

  def valid_token_reset
    return if @user.authenticated?(:reset, params[:id])

    flash[:danger]= I18n.t('messages.failed.password_reset.invalid_token')
    redirect_to root_path
  end

  def check_expiration
    return unless @user.password_reset_expired?

    flash[:danger] = I18n.t('messages.failed.password_reset.expired_reset_token')
    redirect_to new_password_reset_path
  end
end

app/views/password_resets/edit.html.erb
<% provide(:title, t('.reset_password')) %>
<h1><%= t('.reset_password') %></h1>
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, t('.confirmation') %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit t('.update_password'), class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, t('.forgot_password')) %>
<h1><%= t('.forgot_password') %></h1>
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit t('.btn_submit'), class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>