config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root   'static_pages#home'
  get    '/help',      to: 'static_pages#help'
  get    '/about',     to: 'static_pages#about'
  get    '/contact',   to: 'static_pages#contact'
  get    '/signup',    to: 'users#new'
  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'
  resources :users, except: :new do
    member do
      get :following, :followers
    end
  end
  resources :comments,            except: [:index, :show, :new]
  resources :account_activations, only: :edit
  resources :password_resets,     except: [:index, :show, :delete]
  resources :microposts,          only: [:show, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/shared/_comment_form.html.erb
<%= form_for(micropost.comments.build) do |f| %>
  <div class='field'>
    <div>
      <%= gravatar_for(current_user) %>
    </div>
    <div class='row'>
      <div class='col-md-7'>
        <span><%= current_user.name %></span>
        <%= f.hidden_field :micropost_id %>
        <%= f.text_area :content, placeholder: t('shared.placeholder_comment_content'), class: 'form-control custom-comment-area' %>
      </div>
      <div class='col-md-3'>
        <%= f.submit t('shared.btn_comment'), class: 'btn btn-primary custom-comment-btn-submit' %>
        </div>
    </div>
  </div>
<% end %>

app/views/shared/_edit_comment.html.erb
<%= form_for(comment) do |f| %>
  <div class='field'>
    <div>
      <%= f.text_area :content, placeholder: t('shared.placeholder_comment_content'),
        :id => 'commentbox', class: 'custom-comment-area-edit' %>
    </div>
    <%= f.submit t('shared.btn_edit_comment'),
      class: 'btn btn-xs custom-comment-btn-edit btn-primary' %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id='error_explanation'>
    <div class='alert alert-danger'>
      <%= t('shared.count_error', count: pluralize(object.errors.count, t('shared.error'))) %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class='microposts'>
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class='field'>
    <%= f.text_area :content, placeholder: t('shared.placeholder_content') %>
  </div>
  <%= f.submit t('shared.btn_post'), class: 'btn btn-primary' %>
  <span class='picture'>
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

<script type='text/javascript'>
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/<%= Settings.micropost.megabytes %>;
    if (size_in_megabytes > <%= Settings.micropost.picture_size %>){
      alert('<%= I18n.t('shared.picture_max_size') %>');
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class='stats'>
  <%= link_to(following_user_path(@user)) do %>
    <strong id='following' class='stat'>
      <%= @user.following.size %>
    </strong>
    <%= t('shared.following')%>
  <% end %>
  <%= link_to(followers_user_path(@user)) do %>
    <strong id='followers' class='stat'>
      <%= @user.followers.size %>
    </strong>
    <%= t('shared.followers')%>
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: Settings.user.default_user_avatar_size), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to t('shared.my_profile'), current_user %></span>
<span><%= pluralize(current_user.microposts.count, t('shared.micropost')) %></span>