config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root   'static_pages#home'
  get    '/help',      to: 'static_pages#help'
  get    '/about',     to: 'static_pages#about'
  get    '/contact',   to: 'static_pages#contact'
  get    '/signup',    to: 'users#new'
  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'
  resources :users, except: :new do
    member do
      get :following, :followers
    end
  end
  resources :comments,            except: [:index, :show, :new]
  resources :account_activations, only: :edit
  resources :password_resets,     except: [:index, :show, :delete]
  resources :microposts,          only: [:show, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class='footer'>
  <small>
    <%= t('.footer_html', url_tutorials_footer: link_to(t('static_pages.home.homepage_details'),
      Settings.client.home_link), author: link_to(t('.name'), Settings.client.author_link)) %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t('static_pages.about.about'), about_path %></li>
      <li><%= link_to t('static_pages.contact.contact'), contact_path %></li>
      <li><%= link_to t('.new'), Settings.client.news_link %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class='navbar navbar-fixed-top navbar-inverse'>
  <div class='container'>
    <%= link_to t('static_pages.home.sample_app'), root_path, id: 'logo' %>
      <nav>
        <ul class='nav navbar-nav navbar-right'>
          <li><%= link_to t('static_pages.home.home'), root_path %></li>
          <li><%= link_to t('static_pages.help.help'), help_path %></li>
          <% if logged_in? %>
            <li><%= link_to t('layouts.header.user'), users_path %></li>
            <li class='dropdown'>
              <a href='#' class='dropdown-toggle' data-toggle='dropdown'>
                <%= t('.account') %><b class='caret'></b>
              </a>
              <ul class='dropdown-menu'>
                <li><%= link_to t('layouts.header.profile'), current_user %></li>
                <li><%= link_to t('layouts.header.setting'), edit_user_path(current_user) %></li>
                <li class='divider'></li>
                <li>
                  <%= link_to t('layouts.header.logout'), logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to t('static_pages.login'), login_path %></li>
          <% end %>
        </ul>
      </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src='//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js'>
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= full_title(yield(:title)) %>
    </title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class='container'>
      <% flash.each do |message_type, message| %>
        <div class='alert alert-<%= message_type %>'><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>